# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e224f9903b419f1d37c18818f7fea75e6807ab86a163b29b3d488a780a0b52862bce7fdebffb4d6fd7590a2268d13815f51f05ff1a17c7fee871faf98501a20

test:
  secret_key_base: 61e86cf0159059e3e0de1acdfccc3d37e6d9837741f33c9fac80968c2aa1060fe58a0153bce881a0310e8f0445b3f7e4f472f587083f22f31f2365e7a776351d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
